---
title: "compet"
author: "Shriya Kapavarapu"
date: "2024-07-14"
output: html_document
editor_options: 
  chunk_output_type: console
---

Competition: 

```{r}
n = 50

coral.simu1 = rep(NaN, n)

#assigns the first value in vector to 100
coral.simu1[1] <- 200 #exp.simu5
coral.simu1[1]

r1 = 1.0215 #coral growth rate
K1 = 1000

algae.simu1 = rep(NaN, n)
#assigns the first value in vector to 100
algae.simu1[1] <- 50 #exp.simu6
algae.simu1[1]

r2 = 1.025
K2 = 10000
```

```{r}
delta_t <- 1
alpha1 <- 0.3 # effect of coral on algae
beta1 <- -0.3 # effect of algae on coral

sim_df1 <- data.frame(t = 1:n)

for(i in 2:length(coral.simu1)) {
  delta_N1 <- (coral.simu1[i-1] *r1) *((K1-coral.simu1[i-1]+(algae.simu1[i-1]*beta1))/ K1) * delta_t
  coral.simu1[i] <- coral.simu1[i-1] + delta_N1
  
  delta_N2 <- (algae.simu1[i-1] *r2) *((K2-algae.simu1[i-1]+(coral.simu1[i-1]*alpha1))/ K2) * delta_t
  algae.simu1[i] <- algae.simu1[i-1] + delta_N2
}

coral.simu1
print("----------------------------------------------------------")
algae.simu1

sim_df1$coral = coral.simu1
sim_df1$algae = algae.simu1

sim_df_tidy1 <- sim_df1 %>% 
  pivot_longer(cols = coral:algae,
               names_to = "Species",
               values_to = "pop_size")

ggplot(sim_df_tidy1, aes(color = Species)) +
  geom_point(aes(x = t, y = pop_size)) +
  geom_line(aes(x = t , y = pop_size), linetype = "dashed") + 
  theme_minimal() +
  labs(x = "Time (years)",
       y = "Population Size")

#Together
ggplot(sim_df1) +
  geom_point(aes(t , coral), color = "green") +
  geom_line(aes(t , coral), linetype = "dashed", color = "green") +
  geom_point(aes(t , algae), color = "indianred") +
  geom_line(aes(t , algae), linetype = "dashed", color = "indianred") +
  theme_bw()+
  labs(x = "Time" , y = "Population Size")

#ENCHANCED
ggplot(sim_df1) +
  geom_point(aes(t , coral), color = "green") +
  geom_line(aes(t , coral), linetype = "dashed", color = "green") +
  geom_point(aes(t , algae), color = "indianred") +
  geom_line(aes(t , algae), linetype = "dashed", color = "indianred") +
  theme_bw()+
  labs(x = "Time (years)" , y = "Population Size") +
  xlim(0, 10)

```
```{r}
coral.simu2 = rep(NaN, n)
#assigns the first value in vector to 100
coral.simu2[1] <- 200
coral.simu2[1]

r3 = 1.0215
K3 = 1000

algae.simu2 = rep(NaN, n)
#assigns the first value in vector to 100
algae.simu2[1] <- 50
algae.simu2[1]

r4 = 1.025
K4 = 10000

pfish.simu2 = rep(NaN, n)
#assigns the first value in vector to 100
pfish.simu2[1] <- 2000
pfish.simu2[1]

r5 = 1.1
K5 = 13700
```

```{r}
delta_t <- 1

alpha1 <- -0.3 # effect of coral on algae
alpha2 <- 0.5 # coral on pfish
beta1 <- -0.3 # effect of algae on coral
beta2 <- 0.8 # algae on pfish
gamma1 <- -0.5 # pfish on coral
gamma2 <- -0.8 # pfish on algae

sim_df <- data.frame(t = 1:n)

for(i in 2:length(coral.simu2)) {
  
  deltaN1 <- (coral.simu2[i-1] * r3) * ( (K3 - coral.simu2[i-1] + (algae.simu2 * beta1) + (pfish.simu2 * gamma2)) / K3) * delta_t
  coral.simu2[i] <- coral.simu2[i-1] + deltaN1

  deltaN2 <- (algae.simu2[i-1] * r4) * ( (K4 - algae.simu2[i-1] + (coral.simu2 * alpha1) + (pfish.simu2 * gamma1)) / K4) * delta_t
  algae.simu2[i] <- algae.simu2[i-1] + deltaN2

  deltaN3 <- (pfish.simu2[i-1] * r5) * ( (K5 - pfish.simu2[i-1] + (coral.simu2 * alpha2) + (algae.simu2 * beta2)) / K5) * delta_t
  pfish.simu2[i] <- pfish.simu2[i-1] + deltaN3
  
}

sim_df$coral = coral.simu2
sim_df$algae = algae.simu2
sim_df$pfish = pfish.simu2

sim_df_tidy <- sim_df %>% 
  pivot_longer(cols = coral:pfish,
               names_to = "Species",
               values_to = "pop_size")

ggplot(sim_df_tidy, aes(color = Species)) +
  geom_point(aes(x = t, y = pop_size)) +
  geom_line(aes(x = t , y = pop_size), linetype = "dashed") + 
  theme_minimal() +
  labs(x = "Time (years)",
       y = "Population Size")

#all three
ggplot(sim_df) +
  geom_point(aes(t , coral), color = "green") +
  geom_line(aes(t , coral), linetype = "dashed", color = "green") +
  geom_point(aes(t , algae), color = "indianred") +
  geom_line(aes(t , algae), linetype = "dashed", color = "indianred") +
  geom_point(aes(t , pfish), color = "skyblue") +
  geom_line(aes(t , pfish), linetype = "dashed", color = "skyblue") +
  theme_bw()+
  labs(x = "Time (years)",
       y = "Population Size")

#ENCHANCED
ggplot(sim_df) +
  geom_point(aes(t , coral), color = "green") +
  geom_line(aes(t , coral), linetype = "dashed", color = "green") +
  geom_point(aes(t , algae), color = "indianred") +
  geom_line(aes(t , algae), linetype = "dashed", color = "indianred") +
  geom_point(aes(t , pfish), color = "skyblue") +
  geom_line(aes(t , pfish), linetype = "dashed", color = "skyblue") +
  theme_bw()+
  labs(x = "Time (years)",
       y = "Population Size") +
  xlim(0, 10)

```


