---
title: "GROUP 10 SIMULATION"
author: "Shriya, Vivaan, Luke"
date: "2024-07-14"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
``` 

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(ratdat)
library(ggplot2)
library(patchwork)
```

Competition: 

```{r}
n = 50

coral.simu1 = rep(NaN, n)

#assigns the first value in vector to 100
coral.simu1[1] <- 500 #exp.simu5
coral.simu1[1]

r1 = 1.0215 #coral growth rate
K1 = 1000

algae.simu1 = rep(NaN, n)
#assigns the first value in vector to 100
algae.simu1[1] <- 50 #exp.simu6
algae.simu1[1]

r2 = 1.025
K2 = 10000
```

```{r}
delta_t <- 1
alpha1 <- -0.3 # effect of coral on algae
beta1 <- -0.3 # effect of algae on coral

sim_df1 <- data.frame(t = 1:n)

for(i in 2:length(coral.simu1)) {
  delta_N1 <- (coral.simu1[i-1] *r1) *((K1-coral.simu1[i-1]+(algae.simu1[i-1]*beta1))/ K1) * delta_t
  coral.simu1[i] <- coral.simu1[i-1] + delta_N1
  if (coral.simu1[i] < 0) {
    coral.simu1[i] = 0
  }
  
  delta_N2 <- (algae.simu1[i-1] *r2) *((K2-algae.simu1[i-1]+(coral.simu1[i-1]*alpha1))/ K2) * delta_t
  algae.simu1[i] <- algae.simu1[i-1] + delta_N2
}

coral.simu1
print("----------------------------------------------------------")
algae.simu1

sim_df1$coral = coral.simu1
sim_df1$algae = algae.simu1

sim_df_tidy1 <- sim_df1 %>% 
  mutate(coral = coral/K1,
         algae = algae/K2) %>% 
  pivot_longer(cols = coral:algae,
               names_to = "Species",
               values_to = "pop_size")

#together (legend)
together_sim1 <- ggplot(sim_df_tidy1, aes(color = Species)) +
  geom_point(aes(x = t, y = pop_size), size = 4) +
  geom_line(aes(x = t , y = pop_size), linetype = "dashed") + 
  theme_minimal() +
  scale_color_manual(values = c("red", "green")) +
  labs(x = "Time (years)",
       y = "N / K")

together_sim1
```
```{r}
mean_equilibrium <- c(coral.simu1[length(coral.simu1)] / K1, algae.simu1[length(algae.simu1)] / K2)

Species <- c("Coral", "Algae")

data <- data.frame(Species, mean_equilibrium)

equilirium_sim1 <- ggplot(data) +
  geom_col(aes(x = Species, y = mean_equilibrium, fill = Species)) +
  theme_bw() +
  labs(x = "Species",
       y = "Equilibrium N / K") +
  scale_fill_manual(values = c("red", "green"))

equilirium_sim1
mean_equilibrium
```
```{r}
coralsim1 <- ggplot(sim_df1) +
  geom_point(aes(x = t, y = coral/K1), color = "green", size = 4) +
  geom_line(aes(x = t , y = coral/K1), color = "green", linetype = "dashed") + 
  theme_minimal() +
  labs(x = "Time (years)",
       y = "Coral N / K") +
  ylim(0, 1)

coralsim1
```

```{r}
coral.simu2 = rep(NaN, n)
#assigns the first value in vector to 100
coral.simu2[1] <- 500
coral.simu2[1]

r3 = 1.0215
K3 = 1000

algae.simu2 = rep(NaN, n)
#assigns the first value in vector to 100
algae.simu2[1] <- 50
algae.simu2[1]

r4 = 1.025
K4 = 10000

pfish.simu2 = rep(NaN, n)
#assigns the first value in vector to 100
pfish.simu2[1] <- 750
pfish.simu2[1]

r5 = 1.1
K5 = 5000
```

```{r}
delta_t <- 1

alpha1 <- -0.3 # effect of coral on algae
alpha2 <- 0.5 # coral on pfish
beta1 <- -0.3 # effect of algae on coral
beta2 <- 0.8 # algae on pfish
gamma1 <- -0.5 # pfish on coral
gamma2 <- -0.8 # pfish on algae

sim_df <- data.frame(t = 1:n)

for(i in 2:length(coral.simu2)) {
  
  deltaN1 <- (coral.simu2[i-1] * r3) * ( (K3 - coral.simu2[i-1] + (algae.simu2 * beta1) + (pfish.simu2 * gamma1)) / K3) * delta_t
  coral.simu2[i] <- coral.simu2[i-1] + deltaN1
  if (coral.simu2[i] < 0) {
    coral.simu2[i] = 0
  }

  deltaN2 <- (algae.simu2[i-1] * r4) * ( (K4 - algae.simu2[i-1] + (coral.simu2 * alpha1) + (pfish.simu2 * gamma2)) / K4) * delta_t
  algae.simu2[i] <- algae.simu2[i-1] + deltaN2

  deltaN3 <- (pfish.simu2[i-1] * r5) * ( (K5 - pfish.simu2[i-1] + (coral.simu2 * alpha2) + (algae.simu2 * beta2)) / K5) * delta_t
  pfish.simu2[i] <- pfish.simu2[i-1] + deltaN3
  
}

coral.simu2
print("-------------------------------------------------------------")
algae.simu2
print("-------------------------------------------------------------")
pfish.simu2

sim_df$coral = coral.simu2
sim_df$algae = algae.simu2
sim_df$parrotfish = pfish.simu2

sim_df_tidy <- sim_df %>% 
  mutate(coral = coral/K3,
         algae = algae/K4,
         parrotfish = parrotfish/K5) %>% 
  pivot_longer(cols = coral:parrotfish,
               names_to = "Species",
               values_to = "pop_size")

#all three (legend)
together_sim2 <- ggplot(sim_df_tidy, aes(color = Species)) +
  geom_point(aes(x = t, y = pop_size), size = 4) +
  geom_line(aes(x = t , y = pop_size), linetype = "dashed") + 
  theme_minimal() +
  scale_color_manual(values = c("red", "green", "skyblue")) +
  labs(x = "Time (years)",
       y = "N / K")

together_sim2
```

```{r}
mean_equilibrium <- c(coral.simu2[length(coral.simu2)] / K3, algae.simu2[length(algae.simu2)] / K4, pfish.simu2[length(pfish.simu2)] / K5)

mean_equilibrium

Species <- c("Coral", "Algae", "Parrotfish")

data <- data.frame(Species, mean_equilibrium)

equilibrium_sim2 <- ggplot(data) +
  geom_col(aes(x = Species, y = mean_equilibrium, fill = Species)) +
  theme_bw() +
  scale_fill_manual(values = c("red", "green", "skyblue")) +
  labs(x = "Species",
       y = "Equilibrium N / K")

equilibrium_sim2
```
```{r}
coralsim2 <- ggplot(sim_df) +
  geom_point(aes(x = t, y = coral/K3), color = "green", size = 4) +
  geom_line(aes(x = t , y = coral/K3), color = "green", linetype = "dashed") + 
  theme_minimal() +
  labs(x = "Time (years)",
       y = "Coral N / K") +
  ylim(0, 1)

coralsim2
```

```{r}
#together (legend)
together_sim1_1.1 <- ggplot(sim_df_tidy1, aes(color = Species)) +
  geom_point(aes(x = t, y = pop_size), size = 4) +
  geom_line(aes(x = t , y = pop_size), linetype = "dashed") + 
  theme_minimal() +
  scale_color_manual(values = c("red", "green")) +
  labs(x = "Time (years)",
       y = "N / K") +
  ylim(0, 1.1)

together_sim1_1.1

together_sim2_1.1 <- ggplot(sim_df_tidy, aes(color = Species)) +
  geom_point(aes(x = t, y = pop_size), size = 4) +
  geom_line(aes(x = t , y = pop_size), linetype = "dashed") + 
  theme_minimal() +
  scale_color_manual(values = c("red", "green", "skyblue")) +
  labs(x = "Time (years)",
       y = "N / K") +
  ylim(0, 1.1)

together_sim2_1.1
```

```{r}
(together_sim1_1.1 + together_sim2_1.1)
(enhanced_sim1 + enhanced_sim2)
(equilirium_sim1 + equilibrium_sim2)
(coralsim1 + coralsim2)
```

